<?php

namespace AppBundle\Repository;

/**
 * PromotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionRepository extends \Doctrine\ORM\EntityRepository
{
    public function product($id){
        $stmt = $this->getEntityManager()
            ->getConnection()
            ->prepare("SELECT percent FROM promotions WHERE type=1 AND isActive=1 AND madeFor=$id AND activeFrom < NOW() AND activeTo > NOW() ");
        $stmt->execute();
        return $stmt->fetchColumn();
    }
    public function category($id){
        $stmt = $this->getEntityManager()
            ->getConnection()
            ->prepare("SELECT percent FROM promotions WHERE type=2 AND isActive=1 AND madeFor=$id AND activeFrom < NOW() AND activeTo > NOW() ");
        $stmt->execute();
        return $stmt->fetchColumn();
    }
}
