<?php

namespace AppBundle\Repository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\EntityRepository;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends \Doctrine\ORM\EntityRepository
{

    public function getFirst(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM AppBundle:Role p WHERE p.id = 1'
            )
            ->getResult();
    }
}
